### ISSUE TITLE
Contributing guidelines?

### ISSUE THREAD

**Issue by yeungegs** [glyif/shellfish#20]
Since we're working on this test suite as a team, contributing guidelines would be helpful so potential contributors know what to do as they're adding tests and submitting bugs/issues. 

https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by yeungegs** [comment]
I submitted a pull request with first draft of [contributing.md](/Contributing.md) attached

**Comment by yeungegs** [comment]
Submitted pull request with first draft of contributing guidelines
[Pull Request 19](https://github.com/glyif/shellfish/pull/19)

**Comment by johncoleman83** [comment]
Thanks, I just added it and referenced you in the AUTHORS and README
